config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'

  resources :todos, only: [:index, :new, :create] do
    resource :completion, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  def completed?
    completed_at?
  end

  def complete!
    touch :completed_at
  end

  def incomplete!
    update(completed_at: nil)
  end
end

app/models/user.rb
class User
  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user.signed_in?
  end

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo.complete!
    redirect_to todos_path
  end

  def destroy
    todo.incomplete!
    redirect_to todos_path
  end

  private

  def todo
    # .touch here should set timestamp to current time and persist the record
    current_user.todos.find(params[:todo_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.new(todo_params)
    # @todo = Todo.new(todo_params.merge(email: current_email))
    # @todo = Todo.new(todo_params)
    # @todo.email = session[:current_email] if session[:current_email].present?
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAppLewagon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Todos</h1>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%= link_to 'Add a new todo', new_todo_path %>

<% if @todos %>
  <ul class="todos">
    <% @todos.each do |todo| %>
      <li class=<%= 'completed' if todo.completed? %>><%= todo.title %></li>
        <% if todo.completed? %>
          <%= button_to 'Mark incomplete', todo_completion_path(todo), method: :delete %>
        <% else %>
          <%= button_to 'Mark complete', todo_completion_path(todo) %>
        <% end %>
    <% end %>
  </ul>
<% end %>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit 'Submit' %>
<% end %>